name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    if: false   # extension-template is currently not compatible with main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: mobilityduck
      skip_platforms: wasm_mvp;wasm_eh;wasm_threads
    secrets: inherit

  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.2
    with:
      duckdb_version: v1.3.2
      ci_tools_version: v1.3.2
      extension_name: mobilityduck
      skip_platforms: wasm_mvp;wasm_eh;wasm_threads
    secrets: inherit

  code-quality-check:
    name: Code Quality Check
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
    with:
      duckdb_version: v1.3.2
      ci_tools_version: main
      extension_name: mobilityduck
      format_checks: 'format;tidy'
    secrets: inherit
